### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/displaying-associations-rails-lab#11]
i could not render the view #show/1, any idea why?

with following error:
Showing /home/ICanDoAllThingThroughChrist/code/labs/displaying-associations-rails-lab-v-000/app/views/songs/show.html.erb where line #2 raised:

undefined method `name' for nil:NilClass

**Comment by maxwellbenton** [comment]
Hi there,

I'm having difficulty reproducing the issue, but it sounds like it may be related to the way you are accessing your active record relations. 

I'm going to close it for now, but if you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
