### ISSUE TITLE
Issues running specs

### ISSUE THREAD

**Issue by JVThomas** [learn-co-curriculum/displaying-associations-rails-lab#3]
The feature specs would always fail as such...

     Failure/Error: Artist.destroy_all
     
     NameError:
       uninitialized constant Artist
     # ./spec/features/artists_spec.rb:3:in `block (2 levels) in <top (required)>'

I fixed the issue by adding "require 'rails_helper'" to the feature tests. Not sure if it's required or if it's an issue with my environment.

**Comment by AnnJohn** [comment]
hi @JVThomas thanks for raising this. we'll look into this one soon.

**Comment by c1505** [comment]
I had the same error.  Your suggestion fixed it.  Thanks @JVThomas  .
