### ISSUE TITLE
error: +32 spec/features/artists_spec.rb

### ISSUE THREAD

**Issue by WilliamBarela** [learn-co-curriculum/displaying-associations-rails-lab#8]
There is an error in the specs in line 32 of spec/features/artists_spec.rb.
Instead of expecting `2 songs`, the singular `2 song` is expected.

 ``` 
  it "shows the song count for each artist" do
    visit artists_path
    expect(page).to have_content("2 song")
  end
```

**Comment by gj** [comment]
Closed in #9.

Thanks @WilliamBarela !
